name = "sudoku"
version = "1.0.0"

description = "Solving Sudokus in Gleam"
licences = ["Apache-2.0"]

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
birdie = ">= 1.4.1 and < 2.0.0"
iv = ">= 1.3.3 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
